// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package go_micro_srv_test

import (
	errors "github.com/aireet/protoc-gen-go-echo_error/errors"
)

func NewMallErrInvalidParamsError() (err *errors.Exception) {
	err = &errors.Exception{
		Code:       3100001,
		Message:    "无效参数",
		ErrMessage: "MallErrInvalidParams",
	}
	return err
}

func IsMallErrInvalidParams(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Code == 3100001 && e.ErrMessage == "MallErrInvalidParams"
}

func NewMallErrCannotCancelOrdeError() (err *errors.Exception) {
	err = &errors.Exception{
		Code:       3100002,
		Message:    "无法取消该订单",
		ErrMessage: "MallErrCannotCancelOrde",
	}
	return err
}

func IsMallErrCannotCancelOrde(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Code == 3100002 && e.ErrMessage == "MallErrCannotCancelOrde"
}

func NewMallErrNotExistOrdeError() (err *errors.Exception) {
	err = &errors.Exception{
		Code:       3100003,
		Message:    "订单不存在",
		ErrMessage: "MallErrNotExistOrde",
	}
	return err
}

func IsMallErrNotExistOrde(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Code == 3100003 && e.ErrMessage == "MallErrNotExistOrde"
}

func NewMallErrNoPermissionError() (err *errors.Exception) {
	err = &errors.Exception{
		Code:       3100004,
		Message:    "没有操作权限",
		ErrMessage: "MallErrNoPermission",
	}
	return err
}

func IsMallErrNoPermission(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Code == 3100004 && e.ErrMessage == "MallErrNoPermission"
}

func NewMallErrOrderStatusError() (err *errors.Exception) {
	err = &errors.Exception{
		Code:       3100005,
		Message:    "订单状态不合法",
		ErrMessage: "MallErrOrderStatus",
	}
	return err
}

func IsMallErrOrderStatus(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Code == 3100005 && e.ErrMessage == "MallErrOrderStatus"
}
